/* ── YatsuScript WASM API ────────────────────────────── */

/** A single print() output line. */
export interface PrintLine {
  value: string;
  line?: number;
}

/** Result from _eval(). */
export interface EvalResult {
  success: boolean;
  lines: PrintLine[];
  error?: string;
}

/** A node in the parsed AST tree. */
export interface AstNode {
  type: string;
  [key: string]: unknown;
}

/** Result from _parseAst(). */
export interface AstResult {
  success: boolean;
  data: AstNode[];
  error?: string;
}

/** Bytecode listing for one function. */
export interface FunctionBytecode {
  index: number;
  name: string;
  params: number;
  locals: number;
  instructions: string[];
}

/** Result from _disassemble(). */
export interface BytecodeResult {
  success: boolean;
  functions: FunctionBytecode[];
  main: string[];
  error?: string;
}

/** Evaluate source, capture print output as structured lines. */
export function _eval(source: string): EvalResult;

/** Parse source into a structured AST tree. */
export function _parseAst(source: string): AstResult;

/** Compile source and return disassembled bytecode. */
export function _disassemble(source: string): BytecodeResult;

/* ── Generated by wasm-bindgen — do not edit below ──── */

export type InitInput = RequestInfo | URL | Response | BufferSource | WebAssembly.Module;

export interface InitOutput {
  readonly memory: WebAssembly.Memory;
  readonly _disassemble: (a: number, b: number) => any;
  readonly _eval: (a: number, b: number) => any;
  readonly _parseAst: (a: number, b: number) => any;
  readonly __wbindgen_exn_store: (a: number) => void;
  readonly __externref_table_alloc: () => number;
  readonly __wbindgen_externrefs: WebAssembly.Table;
  readonly __externref_drop_slice: (a: number, b: number) => void;
  readonly __wbindgen_free: (a: number, b: number, c: number) => void;
  readonly __wbindgen_malloc: (a: number, b: number) => number;
  readonly __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
  readonly __wbindgen_start: () => void;
}

export type SyncInitInput = BufferSource | WebAssembly.Module;

export function initSync(module: { module: SyncInitInput } | SyncInitInput): InitOutput;

export default function __wbg_init(
  module_or_path?: { module_or_path: InitInput | Promise<InitInput> }
    | InitInput | Promise<InitInput>
): Promise<InitOutput>;
